frr version 8.5
frr defaults traditional
hostname R1
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config

interface eth1
 description Transit-to-R2
 ip address 10.0.1.1/30
 ip ospf area 0
 ip ospf hello-interval 10
 ip ospf dead-interval 40
!
interface eth2
 description LAN-PC1
 ip address 192.168.1.1/24
 ip ospf area 0
 ip ospf passive
!

router ospf
 ospf router-id 1.1.1.1
 network 10.0.1.0/30 area 0
 network 192.168.1.0/24 area 0
 passive-interface eth2
!

ip forwarding
!
line vty
!
end
